name       : pavucontrol
version    : '4.0'
release    : 10
source     :
    - https://gitlab.freedesktop.org/pulseaudio/pavucontrol/-/archive/v4.0/pavucontrol-v4.0.tar.bz2 : 89f7a29aa66ebe2d448ac46b97619b2b00e29e9c8e3f67d609cec843a0170b50
license    : GPL-2.0-only
component  : multimedia.audio
summary    : A GTK volume control for PulseAudio
description: |
    A GTK volume control for PulseAudio
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(sigc++-2.0)
    - intltool
    - lynx
setup      : |
    CXXFLAGS+=' -std=c++11'
    %autogen --enable-gtk3
build      : |
    CXXFLAGS+=' -std=c++11'
    %make
install    : |
    %make_install
