name       : pavucontrol
version    : 3.0
release    : 4
source     :
    - http://freedesktop.org/software/pulseaudio/pavucontrol/pavucontrol-3.0.tar.gz : bb900e4446529fd145e44cf79962f7dbe676a98d86ae7b19f844febf75fb1709
license    : GPL-2.0
component  : multimedia.audio
summary    : A GTK volume control for PulseAudio
description: |
    A GTK volume control for PulseAudio
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(sigc++-2.0)
    - intltool
    - lynx
setup      : |
    CXXFLAGS+=' -std=c++11'
    %patch -p1 < $pkgfiles/unavail.patch
    %configure --enable-gtk3
build      : |
    CXXFLAGS+=' -std=c++11'
    %make
install    : |
    %make_install
