name       : pavucontrol
version    : '5.0'
release    : 11
source     :
    - https://gitlab.freedesktop.org/pulseaudio/pavucontrol/-/archive/v5.0/pavucontrol-v5.0.tar.bz2 : 965e6a4c280c1bc47fdc903d35d2483564a323a7afb1768f0eb58f0722062bd6
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : A GTK volume control for PulseAudio
description: |
    A GTK volume control for PulseAudio
builddeps  :
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libpulse-mainloop-glib)
    - gettext-devel
    - lynx
setup      : |
    CXXFLAGS+=' -std=c++11'
    %autogen --enable-gtk3
build      : |
    CXXFLAGS+=' -std=c++11'
    %make
install    : |
    %make_install
