name       : pavucontrol
version    : 3.0
release    : 6
source     :
    - https://gitlab.freedesktop.org/pulseaudio/pavucontrol/-/archive/v3.0/pavucontrol-v3.0.tar.bz2 : b1899186ce452d39748988082d08810ecf9aa13377117ceef14fdad01a9e395a
license    : GPL-2.0-only
component  : multimedia.audio
summary    : A GTK volume control for PulseAudio
description: |
    A GTK volume control for PulseAudio
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(sigc++-2.0)
    - intltool
    - lynx
setup      : |
    CXXFLAGS+=' -std=c++11'
    %patch -p1 < $pkgfiles/unavail.patch
    %autogen --enable-gtk3
build      : |
    CXXFLAGS+=' -std=c++11'
    %make
install    : |
    %make_install
